### ISSUE TITLE
bad cert handshake failure - {bad_cert,unable_to_match_altnames}

### ISSUE THREAD

**Issue by cultofmetatron** [techgaun/auth0_ex#17]
not sure if this is something with the library or auth0 itself but I'm getting this error when I try to use the management api

```
[error] SSL: :certify: ssl_handshake.erl:1627:Fatal error: handshake failure - {bad_cert,unable_to_match_altnames}

[info] Sent 500 in 456ms
[error] #PID<0.7792.0> running Wixel.Api.Web.Endpoint terminated
Server: dev-api.wixel.io:80 (http)
Request: POST /graphql
** (exit) an exception was raised:
    ** (MatchError) no match of right hand side value: {:error, %{reason: {:tls_alert, 'handshake failure'}}}
        (auth0_ex) lib/auth0_ex/utils.ex:50: Auth0Ex.Utils.fetch_mgmt_token/0
        (auth0_ex) lib/auth0_ex/utils.ex:26: Auth0Ex.Utils.req_header/1
        (auth0_ex) lib/auth0_ex/management/client.ex:6: Auth0Ex.Management.Client.do_request/4
        (wixel_api) lib/wixel_api/web/middleware/authorize_middleware.ex:20: Wixel.Api.Web.AuthorizeMiddleware.call/2
        (absinthe) lib/absinthe/phase/document/execution/resolution.ex:191: Absinthe.Phase.Document.Execution.Resolution.reduce_resolution/1
        (absinthe) lib/absinthe/phase/document/execution/resolution.ex:161: Absinthe.Phase.Document.Execution.Resolution.do_resolve_field/4
        (absinthe) lib/absinthe/phase/document/execution/resolution.ex:147: Absinthe.Phase.Document.Execution.Resolution.do_resolve_fields/6
        (absinthe) lib/absinthe/phase/document/execution/resolution.ex:87: Absinthe.Phase.Document.Execution.Resolution.walk_result/5
        (absinthe) lib/absinthe/phase/document/execution/resolution.ex:57: Absinthe.Phase.Document.Execution.Resolution.perform_resolution/3
        (absinthe) lib/absinthe/phase/document/execution/resolution.ex:25: Absinthe.Phase.Document.Execution.Resolution.resolve_current/3
        (absinthe) lib/absinthe/pipeline.ex:247: Absinthe.Pipeline.run_phase/3
        (absinthe_plug) lib/absinthe/plug.ex:250: Absinthe.Plug.run_query/3
        (absinthe_plug) lib/absinthe/plug.ex:178: Absinthe.Plug.execute/2
        (absinthe_plug) lib/absinthe/plug.ex:139: Absinthe.Plug.call/2
        (phoenix) lib/phoenix/router/route.ex:161: Phoenix.Router.Route.forward/4
        (phoenix) lib/phoenix/router.ex:277: Phoenix.Router.__call__/1
        (wixel_api) lib/wixel_api/web/endpoint.ex:1: Wixel.Api.Web.Endpoint.plug_builder_call/2
        (wixel_api) lib/plug/debugger.ex:123: Wixel.Api.Web.Endpoint."call (overridable 3)"/2
        (wixel_api) lib/wixel_api/web/endpoint.ex:1: Wixel.Api.Web.Endpoint.call/2
        (plug) lib/plug/adapters/cowboy/handler.ex:15: Plug.Adapters.Cowboy.Handler.upgrade/4
```

the offending line is 
```elixir
Auth0Ex.Management.Client.get(current_user.uid)
```
can recreate the error with iex -S mix

```
iex(1)> Auth0Ex.Management.Client.get("facebook|10104480856803932")
[error] SSL: :certify: ssl_handshake.erl:1627:Fatal error: handshake failure - {bad_cert,unable_to_match_altnames}

** (MatchError) no match of right hand side value: {:error, %{reason: {:tls_alert, 'handshake failure'}}}
    (auth0_ex) lib/auth0_ex/utils.ex:50: Auth0Ex.Utils.fetch_mgmt_token/0
    (auth0_ex) lib/auth0_ex/utils.ex:26: Auth0Ex.Utils.req_header/1
    (auth0_ex) lib/auth0_ex/management/client.ex:6: Auth0Ex.Management.Client.do_request/4
```

My guess is its something on auth0's end but can't hurt to ask.

**Comment by techgaun** [comment]
@cultofmetatron I can't really understand why this is happening.. Can you inpsect the URL built on this line: https://github.com/techgaun/auth0_ex/blob/master/lib/auth0_ex/api.ex#L70
I will look into this little more tomorrow but the quick check I just did, its working fine on my end.

**Comment by cultofmetatron** [comment]
the url has sensitive data (jwts and domains and what not) is there a more private channel on where I can send you the data? are you on the elixir slack channel?

Edit: sent it to you on the elixir slack channel

**Comment by bryansray** [comment]
Was there ever any resolution to this issue? I'm receiving the same thing on this line in utils.ex

```elixir
{:ok, %{"access_token" => token}} =
      Auth0Ex.Authentication.Token.client_credentials(client_id, client_secret, base_url(:mgmt))
```

Response:

```
** (exit) an exception was raised:
    ** (MatchError) no match of right hand side value: {:error, %{reason: {:tls_alert, 'handshake failure'}}}
```

**Comment by ssomnoremac** [comment]
@bryansray , crazy timing. It's something having to do the the call to auth0. I noticed the url that @techgaun suggested to log looked like this:

`https://my-domain.auth0.com.auth0.com/tokeninfo?`

do I changed `my-domain.auth0.com` to just `my-domain` in config but now I'm getting
`:error, "Unauthorized", 401`

**Comment by techgaun** [comment]
@bryansray yeah on the config, the domain should be something like:

```
config :auth0_ex,
  domain: "my-domain"
```

As for the `Unauthorized` error, it may be related to your client id/secret (or token if you're using that)
